### ISSUE TITLE
Use environment variable to store variable like password

### ISSUE THREAD

**Issue by stegben** [lydia-code/bizpromote#2]
In `settings.py`, important variables like DB host, port, etc., should be in environment variable, instead of hand-coded in the file.

To be more specific, you might need to
- Prepare a `.env` file, and put important variables in it, for example:
```
BIZPROMOTE_DB_HOST=localhost
BIZPROMOTE_DB_PORT=3306
BIZPROMOTE_DB_NAME=bizpromote
BIZPROMOTE_DB_USER=root
BIZPROMOTE_DB_PASSWORD=cherryButter2
```
Make sure that this `.env` file is ignored in `.gitignore`
- Modify `settings.py`:
```py
import os
…

DATABASES = {
    'default': {
        "ENGINE": 'django.db.backends.mysql',
        "HOST": os.environ.get(‘BIZPROMOTE_DB_HOST’),
        "PORT": os.environ.get(‘BIZPROMOTE_DB_PORT’),
        "NAME": os.environ.get(‘BIZPROMOTE_DB_NAME’),
        "USER": os.environ.get(‘BIZPROMOTE_DB_USER’),
        "PASSWORD": os.environ.get(‘BIZPROMOTE_DB_PASSWORD’),
        'OPTIONS':{
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    },
}
```

- Use `python-dotenv` to load the environment in `.env`. To use it, you may wanna reference [the package page](https://pypi.org/project/python-dotenv/). To be more specific, you need to add these in `manage.py`:
```py
Import dotenv
dotenv.load_dotenv()
```

**Comment by lydia-code** [comment]
done

**Comment by stegben** [comment]
you should provide a `.env.sample` file as a example
